# Generated by Django 6.0.2 on 2026-05-05 04:04

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Konto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bexio_id", models.UUIDField(unique=True)),
                ("bexio_int_id", models.IntegerField(unique=True)),
                ("account_no", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("account_type", models.IntegerField(default=0)),
                ("tax_id", models.IntegerField(blank=True, null=True)),
                ("fibu_account_group_id", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Konto",
                "verbose_name_plural": "Konten",
                "ordering": ["account_no"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalKonto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("bexio_id", models.UUIDField(db_index=True)),
                ("bexio_int_id", models.IntegerField(db_index=True)),
                ("account_no", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("account_type", models.IntegerField(default=0)),
                ("tax_id", models.IntegerField(blank=True, null=True)),
                ("fibu_account_group_id", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Konto",
                "verbose_name_plural": "historical Konten",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLieferantenrechnung",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("bexio_id", models.UUIDField()),
                (
                    "bexio_zeilen_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4),
                ),
                ("dokument_nr", models.CharField(max_length=20)),
                ("titel", models.CharField(max_length=100)),
                ("richtiger_titel", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("rechnungsdatum", models.DateField()),
                ("faelligkeitsdatum", models.DateField(blank=True, null=True)),
                ("lieferant_id", models.IntegerField()),
                ("firmenname", models.CharField(max_length=200)),
                (
                    "verkaeufer_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("waehrung_code", models.CharField(max_length=3)),
                (
                    "rechnungsbetrag",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "ausstehender_betrag",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("ueberfaellig", models.BooleanField(default=False)),
                ("bexio_erstellt_am", models.DateTimeField()),
                ("position", models.IntegerField(default=0)),
                (
                    "betrag",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "zeilen_titel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "steuer_berechnet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buchungskonto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bexio.konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lieferantenrechnung",
                "verbose_name_plural": "historical Lieferantenrechnungen",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Lieferantenrechnung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bexio_id", models.UUIDField()),
                ("bexio_zeilen_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("dokument_nr", models.CharField(max_length=20)),
                ("titel", models.CharField(max_length=100)),
                ("richtiger_titel", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("rechnungsdatum", models.DateField()),
                ("faelligkeitsdatum", models.DateField(blank=True, null=True)),
                ("lieferant_id", models.IntegerField()),
                ("firmenname", models.CharField(max_length=200)),
                (
                    "verkaeufer_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("waehrung_code", models.CharField(max_length=3)),
                (
                    "rechnungsbetrag",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "ausstehender_betrag",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("ueberfaellig", models.BooleanField(default=False)),
                ("bexio_erstellt_am", models.DateTimeField()),
                ("position", models.IntegerField(default=0)),
                (
                    "betrag",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "zeilen_titel",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "steuer_berechnet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "buchungskonto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lieferantenrechnungen",
                        to="bexio.konto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieferantenrechnung",
                "verbose_name_plural": "Lieferantenrechnungen",
                "ordering": ["-rechnungsdatum", "position"],
            },
        ),
    ]
