# Generated by Django 6.0.5 on 2026-09-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bexio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallieferantenrechnung",
            name="richtiger_titel",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="historicallieferantenrechnung",
            name="titel",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lieferantenrechnung",
            name="richtiger_titel",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lieferantenrechnung",
            name="titel",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
