# Generated by Django 6.0.2 on 2026-05-05 04:04

import django.db.models.deletion
import general_manager.measurement.measurement_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stundensatz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jahr", models.PositiveIntegerField(unique=True)),
                (
                    "stundensatz_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("stundensatz_unit", models.CharField(max_length=100)),
                (
                    "stundensatz",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="CHF"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stundensatz",
                "verbose_name_plural": "Stundensätze",
            },
        ),
        migrations.CreateModel(
            name="HistoricalStundensatz",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("jahr", models.PositiveIntegerField(db_index=True)),
                (
                    "stundensatz_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("stundensatz_unit", models.CharField(max_length=100)),
                (
                    "stundensatz",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="CHF"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Stundensatz",
                "verbose_name_plural": "historical Stundensätze",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
