# Generated by Django 6.0.5 on 2026-09-14 08:50

import django.db.models.deletion
import general_manager.measurement.measurement_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kostenart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schluessel", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("ist_ertragsblock", models.BooleanField(default=False)),
                ("konto_nummer", models.IntegerField(blank=True, null=True)),
                ("reihenfolge", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Kostenart",
                "verbose_name_plural": "Kostenarten",
                "db_table": "projekt_kostenart",
                "ordering": ["reihenfolge"],
            },
        ),
        migrations.CreateModel(
            name="ProjektPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Projekt-Phase",
                "verbose_name_plural": "Projekt-Phasen",
                "db_table": "projekt_projektphase",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalKostenart",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("schluessel", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("ist_ertragsblock", models.BooleanField(default=False)),
                ("konto_nummer", models.IntegerField(blank=True, null=True)),
                ("reihenfolge", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Kostenart",
                "verbose_name_plural": "historical Kostenarten",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProjektPhase",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Projekt-Phase",
                "verbose_name_plural": "historical Projekt-Phasen",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Projekt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("auftragsnummer", models.CharField(max_length=50, unique=True)),
                ("jahr", models.PositiveIntegerField()),
                (
                    "offerte_summe_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("offerte_summe_unit", models.CharField(max_length=100)),
                (
                    "offerte_summe",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="CHF"
                    ),
                ),
                (
                    "wv_summe_value",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=10,
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "wv_summe_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "wv_summe",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="CHF", blank=True, default=None, null=True
                    ),
                ),
                (
                    "projektleiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projekte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projekt_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projekte",
                        to="projekt.projektphase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projekt",
                "verbose_name_plural": "Projekte",
            },
        ),
        migrations.CreateModel(
            name="HistoricalKostenPosition",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "offerte_kosten_wert_value",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=10,
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "offerte_kosten_wert_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "offerte_kosten_wert",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="CHF", blank=True, default="0 CHF", null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "art",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projekt.kostenart",
                    ),
                ),
                (
                    "projekt",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projekt.projekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Kostenposition",
                "verbose_name_plural": "historical Kostenpositionen",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProjekt",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("auftragsnummer", models.CharField(db_index=True, max_length=50)),
                ("jahr", models.PositiveIntegerField()),
                (
                    "offerte_summe_value",
                    models.DecimalField(
                        db_index=True, decimal_places=10, max_digits=30
                    ),
                ),
                ("offerte_summe_unit", models.CharField(max_length=100)),
                (
                    "offerte_summe",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="CHF"
                    ),
                ),
                (
                    "wv_summe_value",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=10,
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "wv_summe_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "wv_summe",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="CHF", blank=True, default=None, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projektleiter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projekt_phase",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projekt.projektphase",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Projekt",
                "verbose_name_plural": "historical Projekte",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="KostenPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offerte_kosten_wert_value",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=10,
                        max_digits=30,
                        null=True,
                    ),
                ),
                (
                    "offerte_kosten_wert_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "offerte_kosten_wert",
                    general_manager.measurement.measurement_field.MeasurementField(
                        base_unit="CHF", blank=True, default="0 CHF", null=True
                    ),
                ),
                (
                    "art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kosten_positionen",
                        to="projekt.kostenart",
                    ),
                ),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kosten_positionen",
                        to="projekt.projekt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kostenposition",
                "verbose_name_plural": "Kostenpositionen",
                "unique_together": {("projekt", "art")},
            },
        ),
    ]
