# Generated by Django 6.0.2 on 2026-05-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalkostenart",
            old_name="is_ertragsblock",
            new_name="ist_ertragsblock",
        ),
        migrations.RenameField(
            model_name="kostenart",
            old_name="is_ertragsblock",
            new_name="ist_ertragsblock",
        ),
        migrations.AddField(
            model_name="historicalkostenart",
            name="konto_nummer",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kostenart",
            name="konto_nummer",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
