# Generated by Django 6.0.2 on 2026-05-18 04:23

import general_manager.measurement.measurement_field
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projekt",
            "0002_rename_is_ertragsblock_historicalkostenart_ist_ertragsblock_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalkostenposition",
            name="ist_ertragsblock_wert",
            field=general_manager.measurement.measurement_field.MeasurementField(
                base_unit="CHF", blank=True, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalkostenposition",
            name="ist_ertragsblock_wert_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalkostenposition",
            name="ist_ertragsblock_wert_value",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="kostenposition",
            name="ist_ertragsblock_wert",
            field=general_manager.measurement.measurement_field.MeasurementField(
                base_unit="CHF", blank=True, default=None, null=True
            ),
        ),
        migrations.AddField(
            model_name="kostenposition",
            name="ist_ertragsblock_wert_unit",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kostenposition",
            name="ist_ertragsblock_wert_value",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=10, max_digits=30, null=True
            ),
        ),
    ]
