# Generated by Django 6.0.2 on 2026-05-18 04:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0003_historicalkostenposition_ist_ertragsblock_wert_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalkostenposition",
            old_name="ist_ertragsblock_wert",
            new_name="ist_ertrag_wert",
        ),
        migrations.RenameField(
            model_name="historicalkostenposition",
            old_name="ist_ertragsblock_wert_unit",
            new_name="ist_ertrag_wert_unit",
        ),
        migrations.RenameField(
            model_name="historicalkostenposition",
            old_name="ist_ertragsblock_wert_value",
            new_name="ist_ertrag_wert_value",
        ),
        migrations.RenameField(
            model_name="historicalkostenposition",
            old_name="offerte_position",
            new_name="offerte_kosten_wert",
        ),
        migrations.RenameField(
            model_name="historicalkostenposition",
            old_name="offerte_position_unit",
            new_name="offerte_kosten_wert_unit",
        ),
        migrations.RenameField(
            model_name="historicalkostenposition",
            old_name="offerte_position_value",
            new_name="offerte_kosten_wert_value",
        ),
        migrations.RenameField(
            model_name="kostenposition",
            old_name="ist_ertragsblock_wert",
            new_name="ist_ertrag_wert",
        ),
        migrations.RenameField(
            model_name="kostenposition",
            old_name="ist_ertragsblock_wert_unit",
            new_name="ist_ertrag_wert_unit",
        ),
        migrations.RenameField(
            model_name="kostenposition",
            old_name="ist_ertragsblock_wert_value",
            new_name="ist_ertrag_wert_value",
        ),
        migrations.RenameField(
            model_name="kostenposition",
            old_name="offerte_position",
            new_name="offerte_kosten_wert",
        ),
        migrations.RenameField(
            model_name="kostenposition",
            old_name="offerte_position_unit",
            new_name="offerte_kosten_wert_unit",
        ),
        migrations.RenameField(
            model_name="kostenposition",
            old_name="offerte_position_value",
            new_name="offerte_kosten_wert_value",
        ),
    ]
