# Generated by Django 6.0.5 on 2026-05-22 04:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "projekt",
            "0004_rename_ist_ertragsblock_wert_historicalkostenposition_ist_ertrag_wert_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalkostenposition",
            name="ist_ertrag_wert",
        ),
        migrations.RemoveField(
            model_name="historicalkostenposition",
            name="ist_ertrag_wert_unit",
        ),
        migrations.RemoveField(
            model_name="historicalkostenposition",
            name="ist_ertrag_wert_value",
        ),
        migrations.RemoveField(
            model_name="historicalprojekt",
            name="in_bexio",
        ),
        migrations.RemoveField(
            model_name="kostenposition",
            name="ist_ertrag_wert",
        ),
        migrations.RemoveField(
            model_name="kostenposition",
            name="ist_ertrag_wert_unit",
        ),
        migrations.RemoveField(
            model_name="kostenposition",
            name="ist_ertrag_wert_value",
        ),
        migrations.RemoveField(
            model_name="projekt",
            name="in_bexio",
        ),
    ]
