# Generated by Django 6.0.5 on 2026-08-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0006_projektstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprojekt",
            name="projekt_status",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projekt.projektstatus",
            ),
        ),
        migrations.AddField(
            model_name="projekt",
            name="projekt_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projekte",
                to="projekt.projektstatus",
            ),
        ),
    ]
