# Generated by Django 6.0.5 on 2026-08-28 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0008_backfill_projekt_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprojekt",
            name="auftrag_fertig",
        ),
        migrations.RemoveField(
            model_name="projekt",
            name="auftrag_fertig",
        ),
        migrations.AlterField(
            model_name="projekt",
            name="projekt_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projekte",
                to="projekt.projektstatus",
            ),
        ),
    ]
