# Generated by Django 6.0.5 on 2026-08-28 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0009_projekt_projekt_status_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projektstatus",
            options={
                "ordering": ["id"],
                "verbose_name": "Projekt-Status",
                "verbose_name_plural": "Projekt-Status",
            },
        ),
    ]
