# Generated by Django 6.0.5 on 2026-09-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0010_alter_projektstatus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalkostenposition",
            name="art",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projekt.kostenart",
            ),
        ),
        migrations.AlterField(
            model_name="historicalkostenposition",
            name="projekt",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="projekt.projekt",
            ),
        ),
        migrations.AlterField(
            model_name="kostenposition",
            name="art",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kosten_positionen",
                to="projekt.kostenart",
            ),
        ),
        migrations.AlterField(
            model_name="kostenposition",
            name="projekt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kosten_positionen",
                to="projekt.projekt",
            ),
        ),
    ]
